substitutions:

  ####
  # NAME
  name: espduino-32
  friendly_name: ESPHome
  project_name: deep126.esp32-esp32doit-espduino-esphome-panel
  project_version: "0.0.1"
  board: esp32doit-espduino

  ####
  # PIN MAPPING

  # UNUSED
  # GPIO0:
  # TOUCH
  # Connect to ground on boot to flash
  # outputs PWM signal at boot, must be LOW to enter flashing mode
  
  # LED CONTROL
  # Pulled LOW, RTC, Analog, TOUCH
  status_led: GPIO2

  # BUZZER
  # Add the below to esphome yaml substitution
  buzzer1: $sensor1
  
  # If buzzer needed choose a different sensor in esphome yaml substitution

  # GENERAL PURPOSE GPIO
  sensor1: GPIO1
  # UART0_TXD
  sensor3: GPIO3
  # UART0_RXD
  sensor4: GPIO4
  # Pulled LOW
  # RTC, Analog, TOUCH
  sensor5: GPIO5
  # CAN'T USE WHEN USING SPI0
  # Pulled HIGH
  # VSPI_CS0
  sensor12: GPIO12
  # CAN'T USE WHEN USING SPI1
  # Pulled LOW - Boot fails if pulled HIGH
  # RTC, Analog, TOUCH
  # HSPI_MISO
  sensor13: GPIO13
  # CAN'T USE WHEN USING SPI1
  # RTC, Analog, TOUCH
  # HSPI_MOSI
  sensor14: GPIO14
  # CAN'T USE WHEN USING SPI1
  # RTC, Analog, TOUCH
  # HSPI_CLK
  sensor15: GPIO15
  # CAN'T USE WHEN USING SPI1
  # Pulled HIGH
  # RTC, Analog, TOUCH
  # HSPI_CS0
  # Need to solder pins to use
  sensor16: GPIO16
  # UART2_RXD
  sensor17: GPIO17
  # UART2_TXD
  sensor18: GPIO18
  # CAN'T USE WHEN USING SPI0
  # VSPI_CLK
  sensor19: GPIO19
  # CAN'T USE WHEN USING SPI0
  # VSPI_MISO
  sensor21: GPIO21
  # I2C SDA
  sensor22: GPIO22
  # I2C SCL
  sensor23: GPIO23
  # CAN'T USE WHEN USING SPI0
  # VSPI_MOSI
  sensor25: GPIO25
  # RTC, Analog, DAC Channel 1
  sensor26: GPIO26
  # RTC, Analog, DAC Channel 2
  sensor27: GPIO27
  # RTC, Analog, TOUCH
  sensor32: GPIO32
  # RTC, Analog, TOUCH
  # Need to solder pins to use
  sensor33: GPI033
  # RTC, Analog, TOUCH
  # Need to solder pins to use

  # SPI Bus
  spi_clk0: $sensor18
  spi_cs0: $sensor5
  spi_mosi0: $sensor23
  spi_miso0: $sensor19
  spi_clk1: $sensor14
  spi_cs1: $sensor15
  spi_mosi1: $sensor13
  spi_miso1: $sensor12
  
  # INPUT ONLY PINS
  input1: GPIO34
  # RTC, Analog, Digital
  input2: GPIO35
  # RTC, Analog, Digital
  input3: GPIO36
  # RTC, Analog, Digital
  input4: GPIO39
  # RTC, Analog, Digital

  # INTERNAL - Typically not used, need to solder pins to use
  # Connected to SPI Flash IC
  internal1: GPIO6
  # SPICLK/SDCLK
  internal2: GPIO7
  # SPIQ/SDDATA2
  internal3: GPIO8
  # SPID/SDDATA1
  internal4: GPIO9
  # SPIHD/SDDATA2
  internal5: GPIO10
  # SPIWP/SDDATA3
  internal6: GPIO11
  # SPICS0/SDSMD

  # I2C
  sdapin: $sensor21
  # I2C SDA, GPIO21
  sclpin: $sensor22
  # I2C SCL, GPIO22

packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/esp32-core.yaml
      - packages/core/default-settings.yaml
