substitutions:

  #### BOARD METADATA ####
  name: esp32-s3-wroom-1
  project_name: deep126.esp32-s3-wroom-1-esphome-panel
  project_version: "25.7.3"
  board: esp32-s3-devkitc-1

  #### PIN MAPPING ####
  
  #### UNUSED
  ## STRAP
  # GPIO0 - RTC, STRAP (BOOT), Must be LOW at boot to enter download mode
  # GPIO3 - RTC, Analog, TOUCH, STRAP (JTAG)
  # GPIO45 - STRAP (VSPI)
  # GPIO46 - STRAP (LOG)
  ## SPI Flash and PSRAM - Do not use these GPIOs
  # GPIO26 - Flash/PSRAM SPICS1
  # GPIO27 - Flash/PSRAM SPIHD
  # GPIO28 - Flash/PSRAM SPIWP
  # GPIO29 - Flash/PSRAM SPICS0
  # GPIO30 - Flash/PSRAM SPICLK
  # GPIO31 - Flash/PSRAM SPIQ
  # GPIO32 - Flash/PSRAM SPID

  #### LED ASSIGNMENT
  invert_status_led: "false"
  status_led_1: GPIO2
  # RTC, Analog, TOUCH
  rgb_status_led: $sensor48
  rgb_status_led_length: "1"
  rgb_status_led_order: GRB

  #### BUZZER ASSIGNMENT
  buzzer1: $sensor21

  #### GENERAL PURPOSE GPIO
  sensor1: GPIO1
  # RTC, Analog, TOUCH
  sensor4: GPIO4
  # RTC, Analog, TOUCH
  sensor5: GPIO5
  # RTC, Analog, TOUCH
  sensor6: GPIO6
  # RTC, Analog, TOUCH
  sensor7: GPIO7
  # RTC, Analog, TOUCH
  sensor8: GPIO8
  # RTC, Analog, TOUCH, Default I2C SDA
  sensor9: GPIO9
  # RTC, Analog, TOUCH, Default I2C SCL
  sensor10: GPIO10
  # RTC, Analog, TOUCH
  sensor11: GPIO11
  # RTC, Analog, TOUCH
  sensor12: GPIO12
  # RTC, Analog, TOUCH
  sensor13: GPIO13
  # RTC, Analog, TOUCH
  sensor14: GPIO14
  # RTC, Analog, TOUCH
  sensor15: GPIO15
  # RTC, Analog
  sensor16: GPIO16
  # RTC, Analog
  sensor17: GPIO17
  # RTC, Analog
  sensor18: GPIO18
  # RTC, Analog
  sensor19: GPIO19
  # RTC, Analog, USB_D-
  sensor20: GPIO20
  # RTC, Analog, USB_D+
  sensor21: GPIO21
  # RTC
  sensor35: GPIO35
  # FSPID
  sensor36: GPIO36
  # FSPICLK
  sensor37: GPIO37
  # FSPIQ
  sensor38: GPIO38
  # FSPIWP
  sensor39: GPIO39
  # MTCK
  sensor40: GPIO40
  # MTDO
  sensor41: GPIO41
  # MTDI
  sensor42: GPIO42
  # MTMS
  sensor47: GPIO47
  sensor48: GPIO48
  # Connected to RGB LED in some boards

  #### SPI PINOUT
  spi_clk0: $sensor12
  # GPIO12 - SPI CLK
  spi_cs0: $sensor10
  # GPIO10 - SPI CS
  spi_mosi0: $sensor11
  # GPIO11 - SPI MOSI
  spi_miso0: $sensor13
  # GPIO13 - SPI MISO

  spi_clk1: $sensor36
  # GPIO36 - VSPI CLK
  spi_cs1: $sensor39
  # GPIO39 - VSPI CS
  spi_mosi1: $sensor35
  # GPIO35 - VSPI MOSI
  spi_miso1: $sensor37
  # GPIO37 - VSPI MISO

  #### I2C PINOUT
  sdapin: $sensor8
  # GPIO8 - Default I2C SDA on ESP32-S3
  sclpin: $sensor9
  # GPIO9 - Default I2C SCL on ESP32-S3

  #### UART PINOUT
  uart0_tx: GPIO43
  # GPIO43 - Default UART0 TX
  uart0_rx: GPIO44
  # GPIO44 - Default UART0 RX
  uart1_tx: $sensor17
  # GPIO17 - Default UART1 TX (assignable)
  uart1_rx: $sensor18
  # GPIO18 - Default UART1 RX (assignable)

#### ADDITIONAL PACKAGES ####
packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/esp32-core.yaml
      - packages/core/rgb_status_led.yaml
