substitutions:

  #### BOARD METADATA ####
  name: esp32-c3-super-mini
  project_name: deep126.esp32-c3-super-mini-esphome-panel
  project_version: "26.7.30"
  variant: esp32c3

  #### BOARD SPECIFIC SETTINGS ####

  #### MEMORY
  heap_threshold: "20000"
  
  #### PIN MAPPING ####
  
  #### UNUSED
  # GPIO0:
  # Connect to ground on boot to flash
  # outputs PWM signal at boot, must be LOW to enter flashing mode

  #### LED ASSIGNMENT
  invert_status_led: "true"
  status_led_1: $sensor8

  #### BUZZER ASSIGNMENT
  buzzer1: $sensor1

  #### GENERAL PURPOSE GPIO
  sensor1: GPIO1
  # A1
  sensor2: GPIO2
  # A2
  sensor3: GPIO3
  # A3
  sensor4: GPIO4
  # A4, SCK
  sensor5: GPIO5
  # A5, MISO
  sensor6: GPIO6
  # MOSI
  sensor7: GPIO7
  # SS
  sensor8: GPIO8
  # SDA, LED (active LOW)
  sensor9: GPIO9
  # SCL, Boot (strapping)
  sensor10: GPIO10
  # RX
  sensor20: GPIO20
  # UART/RX
  sensor21: GPIO21
  # UART/TX

  
  #### SPI PINOUT 
  spi_sck: $sensor4
  # GPIO4
  spi_ss: $sensor7
  # GPIO7
  spi_mosi: $sensor6
  # GPIO6
  spi_miso: $sensor5
  # GPIO5
  

  #### I2C PINOUT
  # Moved from default GPIO8/GPIO9 to preserve onboard LA and BOOT button
  sdapin: $sensor2
  sclpin: $sensor3

  #### UART PINOUT
  uart_rx: $sensor20
  uart_tx: $sensor21

#### ADDITIONAL PACKAGES
packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/esp32-core.yaml
