substitutions:

  ####
  # NAME
  name: esp32doit-espduino
  friendly_name: ESPHome
  project_name: deep126.esp32-esp32doit-espduino-esphome-panel
  project_version: "0.0.1"
  board: esp32doit-espduino

  ####
  # PIN MAPPING
  
  # LED CONTROL
  # Pulled LOW, RTC, Analog, TOUCH
  status_led: GPIO2

  # BUZZER
  # Add the below to esphome yaml substitution
  # buzzer1: GPIO0
  # If buzzer needed choose a different sensor in esphome yaml substitution

  # GENERAL PURPOSE GPIO
  # UART0_TXD
  sensor1: GPIO1
  # UART0_RXD
  sensor2: GPIO3
  # Pulled LOW
  # RTC, Analog, TOUCH
  sensor3: GPIO4
  # CAN'T USE WHEN USING SPI0
  # Pulled HIGH
  # VSPI_CS0
  sensor4: GPIO5
  # CAN'T USE WHEN USING SPI1
  # Pulled LOW - Boot fails if pulled HIGH
  # RTC, Analog, TOUCH
  # HSPI_MISO
  sensor5: GPIO12
  # CAN'T USE WHEN USING SPI1
  # RTC, Analog, TOUCH
  # HSPI_MOSI
  sensor6: GPIO13
  # CAN'T USE WHEN USING SPI1
  # RTC, Analog, TOUCH
  # HSPI_CLK
  sensor7: GPIO14
  # CAN'T USE WHEN USING SPI1
  # Pulled HIGH
  # RTC, Analog, TOUCH
  # HSPI_CS0
  # Need to solder pins to use
  sensor8: GPIO15
  # UART2_RXD
  sensor9: GPIO16
  # UART2_TXD
  sensor10: GPIO17
  # CAN'T USE WHEN USING SPI0
  # VSPI_CLK
  sensor11: GPIO18
  # CAN'T USE WHEN USING SPI0
  # VSPI_MISO
  sensor12: GPIO19
  # I2C SDA
  sensor13: GPIO21
  # I2C SCL
  sensor14: GPIO22
  # CAN'T USE WHEN USING SPI0
  # VSPI_MOSI
  sensor15: GPIO23
  # RTC, Analog, DAC Channel 1
  sensor16: GPIO25
  # RTC, Analog, DAC Channel 2
  sensor17: GPIO26
  # RTC, Analog, TOUCH
  sensor18: GPIO27
  # RTC, Analog, TOUCH
  # Need to solder pins to use
  sensor19: GPIO32
  # RTC, Analog, TOUCH
  # Need to solder pins to use
  sensor20: GPI033

  # SPI Bus
  # GPI018
  spi_clk0: $sensor11
  # GPI05
  spi_cs0: $sensor4
  # GPI023
  spi_mosi0: $sensor15
  # GPI019
  spi_miso0: $sensor12
  # GPI014
  spi_clk1: $sensor7
  # GPI015
  spi_cs1: $sensor8
  # GPI013
  spi_mosi1: $sensor6
  # GPI012
  spi_miso1: $sensor5
  
  # INPUT ONLY PINS
  # RTC, Analog
  input1: GPIO34
  # RTC, Analog
  input2: GPIO35
  # RTC, Analog
  input3: GPIO36
  # RTC, Analog
  input4: GPIO39

  # INTERNAL - Typically not used, need to solder pins to use
  # Connected to SPI Flash IC
  # SPICLK/SDCLK
  internal1: GPIO6
  # SPIQ/SDDATA2
  internal2: GPIO7
  # SPID/SDDATA1
  internal3: GPIO8
  # SPIHD/SDDATA2
  internal4: GPIO9
  # SPIWP/SDDATA3
  internal5: GPIO10
  # SPICS0/SDSMD
  internal6: GPIO11

  # I2C
  # I2C SDA, GPIO21
  sdapin: $sensor13
  # I2C SCL, GPIO22
  sclpin: $sensor14

packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/esp32-core.yaml
      - packages/core/esp-default-settings.yaml
      - packages/core/esp32-connectivity.yaml
      - packages/core/esp32-buzzer.yaml
      - packages/core/buzzer-sounds.yaml
