substitutions:

  ####
  # NAME
  name: nodemcuv2
  friendly_name: ESPHome
  project_name: deep126.esp8266-nodemcuv2-esphome-panel
  project_version: "0.0.1"
  board: nodemcuv2
  invert_status_led: "true"

  ####
  # PIN MAPPING
  
  # LED CONTROL
  status_led: $sensor4
  # D4, GPIO2, TXD1
  # Output only
  # Restricted if high on boot
  # Weak Pull Up
  
  # BUZZER
  buzzer1: GPIO1
  # GPIO1, TX, TXD0

  # GENERAL PURPOSE GPIO
  sensor0: D0
  # GPIO16, Wake
  # Has pull-down (but no pull-up) resistor
  # Weak Pull Down
  sensor1: D1
  # GPIO5, SCL
  sensor2: D2
  # GPIO4, SDA
  sensor3: D3
  # GPIO0, FLASH
  # Restricted if high on boot
  # Weak Pull Up
  sensor4: D4
  # GPIO2, TXD1
  # Output only
  # Restricted if high on boot
  # Weak Pull Up
  sensor5: D5
  # GPIO14, HSCLK
  # Weak Pull Up
  sensor6: D6
  # GPIO12, HMISO
  # Weak Pull Up
  sensor7: D7
  # GPIO13, CTSO, HMOSI
  # Weak Pull Up
  sensor8: D8
  # GPIO15, RTS0, HCS
  # Restricted if low on boot
  # Weak Pull Up

  # INPUT ONLY PINS
  input1: A0
  # A0, ADC0
  # Analog input only

  # I2C
  sdapin: $sensor2
  sclpin: $sensor1

packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/esp8266-core.yaml
      - packages/core/default-settings.yaml
