substitutions:

  #### BOARD METADATA ####
  name: konnected-esp8266
  friendly_name: Konnected Panel
  project_name: deep126.esp8266-konnected-esphome-panel
  project_version: "25.5.31"
  board: nodemcuv2
  invert_status_led: "true"

  #### PIN MAPPING ####
  
  #### LED ASSIGNMENT
  status_led_1: D4
  # GPIO2, TXD1
  # Output only
  # Restricted if high on boot
  # Weak Pull Up

  #### BUZZER ASSIGNMENT
  buzzer1: $sensor5
  # If using buzzer can't use sensor 5
  siren: D8
  # GPIO15, RTS0, HCS
  # Restricted if low on boot
  # Weak Pull Up

  #### GENERAL PURPOSE GPIO
  sensor1: D1
  # GPIO5, SCL - Zone 1
  sensor2: D2
  # GPIO4, SDA - Zone 2
  sensor3: D5
  # GPIO14, HSCLK - Zone 3
  # Weak Pull Up
  sensor4: D6
  # GPIO12, HMISO - Zone 4
  # Weak Pull Up
  sensor5: D7
  # GPIO13, CTSO, HMOSI- Zone 5
  # Weak Pull Up
  
  #### INPUT ONLY PINS
  input1: D9
  # GPIO3, RX, RXD0 - Zone 6

#### ADDITIONAL PACKAGES
packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/esp8266-core.yaml
      - packages/core/siren.yaml
