substitutions:

  ####
  # NAME
  name: konnected-esp8266
  friendly_name: Konnected Panel
  project_name: deep126.esp8266-konnected-esphome-panel
  project_version: "0.0.1"
  board: nodemcuv2

  ####
  # PIN MAPPING
  
  # LED CONTROL
  # GPIO2, TXD1
  # Output only
  # Restricted if high on boot
  # Weak Pull Up
  status_led: D4


  # GPIO5, SCL - Zone 1
  sensor1: D1
  # GPIO4, SDA - Zone 2
  sensor2: D2
  # GPIO14, HSCLK - Zone 3
  # Weak Pull Up
  sensor3: D5
  # GPIO12, HMISO - Zone 4
  # Weak Pull Up
  sensor4: D6
  # GPIO13, CTSO, HMOSI- Zone 5
  # Weak Pull Up
  sensor5: D7
  
  # BUZZER
  # If using buzzer can't use sensor 5
  buzzer1: $sensor5

  # GPIO3, RX, RXD0 - Zone 6
  input1: D9

  # GPIO15, RTS0, HCS
  # Restricted if low on boot
  # Weak Pull Up
  siren: D8

packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/esp8266-core.yaml
      - packages/core/default-settings.yaml
      - packages/core/connectivity.yaml
      - packages/core/siren.yaml
