substitutions:

  ####
  # NAME
  name: esphome-panel
  friendly_name: ESPHome Panel
  project_name: deep126.esp8266-nodemcuv2-esphome-panel
  project_version: "0.0.1"
  board: nodemcuv2

  ####
  # PIN MAPPING
  
  # LED CONTROL
  # GPIO2, TXD1
  # Output only
  # Restricted if high on boot
  # Weak Pull Up
  status_led: D4

  # BUZZER
  # GPIO1, TX, TXD0
  buzzer1: GPIO1

  # GENERAL PURPOSE GPIO
  # GPIO0, FLASH
  # Restricted if high on boot
  # Weak Pull Up
  sensor1: D3
  # GPIO4, SDA
  sensor2: D2
  # GPIO5, SCL
  sensor3: D1
  # GPIO6, CLK, SCLK, SDCLK
  # Weak Pull Up
  sensor4: GPIO6
  # GPIO12, HMISO
  # Weak Pull Up
  sensor5: D6
  # GPIO13, CTSO, HMOSI
  # Weak Pull Up
  sensor6: D7
  # GPIO14, HSCLK
  # Weak Pull Up
  sensor7: D5
  # GPIO15, RTS0, HCS
  # Restricted if low on boot
  # Weak Pull Up
  sensor8: D8
  # GPIO16, wake
  # Has pull-down (but no pull-up) resistor
  # Weak Pull Down
  sensor9: D0

  # INPUT ONLY PINS
  # GPIO3, RX, RXD0
  input1: D9
  # A0, ADC0
  # Analog input only
  input2: A0

  # I2C
  # GPIO9, SDD2
  # sdapin: GPIO9
  # GPIO10, SDD3
  # sclpin: GPIO10

packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/esp8266-core.yaml
      - packages/core/esp-default-settings.yaml
      - packages/core/esp8266-connectivity.yaml
      - packages/core/esp8266-buzzer.yaml
