####################################################################
########## REPLACE ORIGINAL CONFIG VALUES FROM THIS POINT ##########
####################################################################

# Delete everything through 'ap:' and replace with the following 

# Set these substitutions as needed, examples are provided
substitutions:
  # Choose room/area for Home Assistant to assign
  area: Test Room
  device_name: test-room
  device_friendly: $area

packages:

  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files:
      # BASE
      # This package will set up board specific core features.
      # Uncomment which packages you want to include
      - packages/base/esp8266-nodemcuv2-base.yaml
      # - packages/base/esp32-esp32doit-espduino-base.yaml
      # - packages/core/mqtt.yaml
      # - packages/core/ble_mqtt_room.yaml

# Decide how the device should be named, examples are provided
# The board name (name/friendly name) has been predefined in the base files
# Board names will be added to the end of all names/friendly names in order to differentiate
esphome:
  name: ${device_name}-${name}
  friendly_name: ${device_friendly} ${friendly_name}
  area: ${area}
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: 0.0.0.0

####################################################################
##### FROM THIS POINT ON DO NOT REPLACE ORIGINAL CONFIG VALUES #####
####################################################################

# The only thing we want to keep from the original config is the custom ap

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test-Room"
    password: "XXXXXXXXXXXX"

captive_portal:

### FROM THIS POINT ADD SENSORS/COMPONENTS ####

binary_sensor:

  - id: kitchen_door_contact
    name: Kitchen Door Contact Sensor
    pin:
      number: $sensor1
      mode: INPUT_PULLUP
    platform: gpio
    device_class: door
    filters:
      - delayed_on_off: $debounce_time

  - id: kitchen_motion
    name: Kitchen Motion Sensor
    pin:
      number: $sensor2
      mode: INPUT_PULLUP
    platform: gpio   
    device_class: motion
    filters:
      - delayed_on: $debounce_time
      - delayed_off: $delayed_off_time

switch:
  # Relay
  - platform: gpio
    name: "Guest Closet Lights"
    pin: $sensor3
    inverted: true
    id: guest_closet_relay

  - platform: gpio
    name: "Panel Lights"
    id: panel_light_strip
    pin:
      number: $sensor4
    on_turn_on:
      - light.turn_on: panel_led
    on_turn_off:
      - light.turn_off: panel_led
    
  - platform: template
    name: "${friendly_name} Buzzer Enabled"
    id: buzzer_enabled
    icon: mdi:volume-high
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config

sensor:
  - platform: dht
    pin: $sensor5
    temperature:
      name: "${friendly_name} Temperature"
      id: test_temperature
    humidity:
      name: "${friendly_name} Humidity"
      id: test_humidity
    update_interval: 60s
    model: DHT22


