substitutions:
  #### SETTINGS
  debounce_time: 200ms
  delayed_off_time: 5s

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

safe_mode:

logger:
  level: INFO

binary_sensor:
  - platform: status
    name: "Status"
    entity_category: diagnostic
  - platform: template
    name: "Low Memory Warning"
    lambda: |-
      return ESP.getFreeHeap() < 120000;
    update_interval: 60s
    entity_category: diagnostic
    device_class: problem
    
text_sensor:
  - platform: template
    name: "Device ID"
    id: device_id
    entity_category: diagnostic
    update_interval: never
  - platform: version
    hide_timestamp: true
    name: "ESPHome Version"
    entity_category: diagnostic
  - platform: template
    name: "Last Reset Reason"
    lambda: |-
      return ESP.getResetReason();
    update_interval: 60s
    entity_category: diagnostic
    
button:
  - platform: restart
    name: "Restart"
    entity_category: config
  - platform: safe_mode
    name: "Restart (Safe Mode)"
    entity_category: config

  #### STATUS LED
globals:
  - id: blink_on_state
    type: bool
    restore_value: no
    initial_value: "true"

switch:
  - platform: template
    name: "Blink On State Status"
    restore_mode: ALWAYS_ON
    lambda: |-
      return id(blink_on_state);
    turn_on_action:
      - lambda: |-
          id(blink_on_state) = true;
    turn_off_action:
      - lambda: |-
          id(blink_on_state) = false;
          
light:
  - platform: status_led
    name: "Status LED Light"
    id: status_led_light
    pin:
      number: $status_led
      inverted: $invert_status_led

script:
  - id: blink_status_led
    then:
      - if:
          condition:
            lambda: return id(blink_on_state);
          then:
            - light.toggle: status_led_light
            - delay: 100ms
            - light.toggle: status_led_light

  #### BUZZER
output:
  - platform: $buzzer_platform
    pin: $buzzer1
    id: rtttl_out

rtttl:
  output: rtttl_out

packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/connectivity.yaml
      - packages/core/buzzer-sounds.yaml
