substitutions:

  ####
  # SETTINGS
  debounce_time: 200ms
  delayed_off_time: 5s

  ####
  # STATUS LED
globals:
  - id: blink_on_state
    type: bool
    initial_value: "true"

switch:
  - platform: template
    name: "Blink On State"
    lambda: |-
      return id(blink_on_state);
    turn_on_action:
      - lambda: |-
          id(blink_on_state) = true;
    turn_off_action:
      - lambda: |-
          id(blink_on_state) = false;
          
light:
  - platform: status_led
    id: status_led_light
    pin:
      number: $status_led
      inverted: $invert_status_led

script:
  - id: blink_status_led
    then:
      - if:
          condition:
            lambda: return id(blink_on_state);
          then:
            - light.turn_on: status_led_light
            - delay: 100ms
            - light.turn_off: status_led_light

packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/connectivity.yaml
