esphome:
  project:
    name: $project_name
    version: $project_version
  on_boot:
    priority: 600.0
    then:
      - text_sensor.template.publish:
          id: device_id
          state: !lambda 'return get_mac_address();'
      - wait_until:
          api.connected:
      - logger.log: API is connected!
      - rtttl.play: $success_beep

esp32:
  board: ${board}

sensor:
  - platform: esp32_hall
    name: "ESP32 Hall Sensor" # optional but fun
    
packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/default-settings.yaml
      - packages/core/esp32-buzzer.yaml
