substitutions:
  buzzer_platform: ledc
  
esp32:
  board: $board
  cpu_frequency: 240MHz
  framework:
    type: esp-idf

packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/default-settings.yaml
      - packages/core/i2s-audio.yaml
      - packages/core/i2s-microphone.yaml
      - packages/core/i2s-speaker.yaml
      
