substitutions:
  buzzer_platform: ledc
  
esp32:
  board: ${board}

sensor:
  - platform: esp32_hall
    name: "ESP32 Hall Sensor" # optional but fun
    
packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/default-settings.yaml
