substitutions:
  buzzer_platform: esp8266_pwm

esp8266:
  board: ${board}
  restore_from_flash: True

packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/default-settings.yaml
