esphome:
  name: ${name}
  name_add_mac_suffix: True
  friendly_name: ${friendly_name}
  area: ${area}
  project:
    name: $project_name
    version: $project_version
  on_boot:
    priority: -100.0
    then:
      - wait_until:
          api.connected:
      - logger.log: API is connected!
      - rtttl.play: $success_beep
      - text_sensor.template.publish:
          id: device_id
          state: !lambda 'return get_mac_address();'

esp8266:
  board: ${board}
  restore_from_flash: True

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    entity_category: diagnostic

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    entity_category: diagnostic

text_sensor:
  - platform: template
    name: "${friendly_name} Device ID"
    id: device_id
    entity_category: diagnostic
    update_interval: never
  - platform: version
    hide_timestamp: true
    name: "${friendly_name} ESPHome Version"
    entity_category: diagnostic

button:
  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: config
