esphome:
  project:
    name: $project_name
    version: $project_version
  on_boot:
    priority: 600.0
    then:
      - text_sensor.template.publish:
          id: device_id
          state: !lambda 'return get_mac_address();'
      - wait_until:
          api.connected:
      - logger.log: API is connected!
      - rtttl.play: $success_beep

esp8266:
  board: ${board}
  restore_from_flash: True

packages:
  remote_package:
    url: http://github.com/deep126/esphome
    ref: master
    refresh: 5min
    files: 
      - packages/core/components.yaml
      - packages/core/default-settings.yaml
      - packages/core/esp8266-buzzer.yaml
