sensor:
  - platform: template
    name: "Free Heap"
    lambda: |-
      return ESP.getFreeHeap();
    unit_of_measurement: "bytes"
    update_interval: 60s
  - platform: template
    name: "Max Alloc Heap"
    lambda: |-
      return ESP.getMaxAllocHeap();
    unit_of_measurement: "bytes"
    update_interval: 60s
